package com.degressly.proxy.constants;

public enum Encoding {

	INT_1, INT_2, INT_3, INT_4, INT_6, INT_8, INT_LENGTH_ENCODED,

	STRING_FIXEDLENGTH, STRING_NULL_TERMINATED, STRING_VARIABLELENGTH, STRING_LENGTH_ENCODED, STRING_RESTOFPACKET

}
